#!/usr/bin/bash

all_hills=$(echo HILLS.* | tr ' ' ',')
echo "Summing hills $all_hills"

plumed sum_hills --hills $all_hills --kt 2.494339 --mintozero --min 0.18,0.18 --max 1.12,1.12 --bin 94,94 &> sum_hills.log

plumed_exit_status=$?
if [ $plumed_exit_status -ne 0 ]; then
  echo "plumed sum_hills failed with exit status $plumed_exit_status. Check sum_hills.log for more information."
  exit $plumed_exit_status
else
  echo "plumed sum_hills completed successfully"
fi