#!/usr/bin/env bash
print_usage() {
    echo "Usage: $0 <input_gbw_water> <input_gbw_vacuum>"
    echo "This script runs Multiwfn on the specified gbw or molden-input('orca_2mkl YOUR_FILE.gbw -molden') file."
}

script_path=$(readlink -f "$0")
script_folder=$(dirname "$script_path")
ESPiso_script="$script_folder/multiwfn_ESPiso.sh"
diff_script="$script_folder/multiwfn_diff.sh"
output_density_diff="diff_density.cub"
output_esp_diff="diff_totesp.cub"

if [ "$#" -ne 2 ]; then
    print_usage
    exit 1
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    print_usage
    exit 0
fi

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Error: Both input .cub files must be specified."
    print_usage
    exit 1
fi

input_gbw_water="$1"
input_gbw_vacuum="$2"

if ! [ -f "$input_gbw_water" ]; then
    echo "Input file '$input_gbw_water' does not exist."
    exit 1
fi

if ! [ -f "$input_gbw_vacuum" ]; then
    echo "Input file '$input_gbw_vacuum' does not exist."
    exit 1
fi

if ! which Multiwfn > /dev/null; then
    echo "Multiwfn is not installed or not in PATH."
    exit 1
fi

input_base_water=$(basename "$input_gbw_water" .gbw)
input_base_water=$(basename "$input_base_water" .molden.input)
input_density_water="${input_base_water}_density.cub" # Generated by ESPiso
input_esp_water="${input_base_water}_totesp.cub" # Generated by ESPiso

input_base_vacuum=$(basename "$input_gbw_vacuum" .gbw)
input_base_vacuum=$(basename "$input_base_vacuum" .molden.input)
input_density_vacuum="${input_base_vacuum}_density.cub" # Generated by ESPiso
input_esp_vacuum="${input_base_vacuum}_totesp.cub" # Generated by ESPiso

$ESPiso_script $input_gbw_water
$ESPiso_script $input_gbw_vacuum

# $diff_script $input_density_water $input_density_vacuum
# mv grid_diff.cub $output_density_diff
#cp $input_density_water $output_density_diff

$diff_script $input_esp_water $input_esp_vacuum
mv grid_diff.cub $output_esp_diff

echo "Multiwfn execution for grid difference completed successfully."
echo "Output files: $output_density_diff, $output_esp_diff"

